/*job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/anshulc55/Jenkins_Upgradev3.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
 //       archiveArtifacts '**/*.jar'
 //   }
//}



job('First-Grovy-DSL-SeedJob') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is my first seed job")
    logRotator(1,7)
    jdk('Java 8')

    scm {
        git("https://github.com/ijabs1/Jenkins_Upgradev3.git", 'master')
    }
    // Logrotator
    options{
        buildDiscarder(logRotator(numToKeepStr:'1'), logRotator(daysToKeepStr:'7'))
    }
    triggers {
        scm('* * * * *')
    }
    // for passing environment variables
    // environment {
    //     delete
    // }
    steps {
        maven('clean package', 'java-tomcat-sample/pom.xml)
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.war'
    }
}
job.getPublishersList().add(new WorkspaceCleanup())
