job('First-Grovy-DSL-SeedJob') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is my first seed job")
    logRotator(1,7)
    jdk('Java 8')

    scm {
        git("https://github.com/ijabs1/Jenkins_Upgradev3.git", 'master')
    }
    // Logrotator
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'java-tomcat-sample/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.war'
    }
}
